### ISSUE TITLE
Bug: "now" is offset by double the timezone offset

### ISSUE THREAD

**Issue by Cody-Duncan** [erhanbaris/smartcalc#15]
Expected - The time right now is:
14:00 PST (GMT-8)
22:00 UTC

Actual - SmartCalc reports the time as:
06:00 PST (GMT-8 minus another 8 hours)
14:00 UTC (which is minus 8 hours

Seems like it might be doubling the GMT time offset for the time "now"?
I can't say for certain because I'd have to test this from another time zone to see if it's off by double that zone's offset.

![image](https://user-images.githubusercontent.com/1480323/156660037-4825cddd-c3df-424c-a2ea-47de45f4e272.png)

**Comment by erhanbaris** [comment]
Thanks for reporting this issue.
Issue solved and merged into main branch. It is ready to use.
