### ISSUE TITLE
[Request] Upload the code to crates.io to be able to `cargo install` without hassle

### ISSUE THREAD

**Issue by BLucky-gh** [erhanbaris/smartcalc#2]
At the moment I can't find this project as a crate on crates.io under any intuitive name, which means I can't just `cargo install` this project and have to `git pull` the source and then compile it manually. Uploading this to `crates.io` would be very helpful.

**Comment by erhanbaris** [comment]
Hi
I added project to [crate](https://crates.io/).

Here is the Cargo manifest:
```toml
[dependencies]
smartcalc = "1"
```
