### ISSUE TITLE
Support for different date formats in date calculations

### ISSUE THREAD

**Issue by jdc1999** [erhanbaris/smartcalc#29]
Could you add support for different date formats for the date calculations feature? For example:

- month/day/year format
- year/month/day format
- Delimiters other than a slash. For example, dates written as yyyy-mm-ddd (using slashes) or yyyy.mm.dd (using dots).

Supporting different formats and delimiters would make the app more accessible to people who do not use the day/month/year format that the app uses by default.

It would be great if these other date formats were also supported in the compiled app version https://github.com/erhanbaris/smartcalc-app.

BTW, this is a great app! Thank you for making it!

**Comment by erhanbaris** [comment]
Hi
Thank you for your interest on this project. I am working on new GUI and it will have more functionality than current version. I will integrate personalized output but that can take a while because of the stabilizing the new GUI.

**Comment by erhanbaris** [comment]
GUI updated! You can try it right now, I hope that is what you expected.

**Comment by jdc1999** [comment]
The new GUI looks great and so does the parser for day/month/year. One more small request - could you create an option to display the day of the week in the output? Often I need to add x days to a date, but if the result falls on a weekend, I'd need to know that for a next step in the calculation.  Just to be clear, this would be for output only. I don't need a day of the week in the input.
